### ISSUE TITLE
args

### ISSUE THREAD

**Issue by seulchanson** [mohamedr002/SLARDA#3]
The SSL folder doesn't have args.py.

**Comment by PeinMulan** [comment]
The args.py is in the Autorgressive_Adaptation folder.  Can the author open source the code for data preprocessing and the preprocessed data?

**Comment by mohamedr002** [comment]
Done

**Comment by mohamedr002** [comment]
https://github.com/mohamedr002/SLARDA/tree/main/Autorgressive_Adaptation/dataloader
